#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""
Scaffold a new Claude skill from a JSON spec.

Usage:
    uv run scaffold.py --spec spec.json --out ./<skill-name>/

Writes:
    <out>/SKILL.md
    <out>/scripts/<each code-step script>   (stub if not present)
    <out>/evals/trigger.json                 (placeholder)

Idempotent: never overwrites existing script stubs or eval files. Always
re-renders SKILL.md from the spec.
"""

import argparse
import json
import sys
from pathlib import Path

TEMPLATE = """---
name: {name}
description: {description}
---

# {title}

{gotchas_section}

## Steps

{steps_rendered}

## Inference Call Log

<!--
Logging hooks (MVP scaffold).

Each inference call below should log: cost, input hash, output, latency.
The log-writer is not built in MVP — record entries manually as the skill
runs, or wire up the writer when the observability layer ships.

Per ~/.claude/rules/skills.md §9.
-->
"""


def render_gotchas(gotchas):
    if not gotchas:
        return ""
    lines = ["## Gotchas", ""]
    for g in gotchas:
        lines.append(f"- {g}")
    return "\n".join(lines) + "\n"


def render_step(step):
    n = step["n"]
    name = step["name"]
    type_ = step["type"]
    rationale = step.get("rationale", "")

    block = [f"### Step {n}: {name} ({type_})", "", rationale]

    if type_ in ("inference", "hybrid"):
        c = step.get("contract", {})
        if c:
            block.extend([
                "",
                "**Inference contract:**",
                f"- **Input:** {c.get('input', '')}",
                f"- **Output:** {c.get('output', '')}",
                f"- **Why not code:** {c.get('justification', '')}",
            ])

    if type_ in ("code", "hybrid"):
        script = step.get("script")
        if script:
            block.extend(["", f"**Script:** `{script}`"])

    return "\n".join(block)


def title_case(s):
    return " ".join(w.capitalize() for w in s.replace("-", " ").split())


def write_script_stub(path: Path, step_name: str):
    if path.exists():
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    stub = f'''#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""
Stub for step: {step_name}

Generated by compile-skill. Implement this step's deterministic logic.
"""

import sys


def main():
    raise NotImplementedError("Implement: {step_name}")


if __name__ == "__main__":
    main()
'''
    path.write_text(stub)
    return True


def scaffold(spec, out_dir):
    out = Path(out_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)

    steps_rendered = "\n\n".join(render_step(s) for s in spec.get("steps", []))
    skill_md = TEMPLATE.format(
        name=spec["name"],
        description=spec["description"],
        title=title_case(spec["name"]),
        gotchas_section=render_gotchas(spec.get("gotchas", [])),
        steps_rendered=steps_rendered,
    )
    (out / "SKILL.md").write_text(skill_md)

    created_stubs = []
    for s in spec.get("steps", []):
        if s["type"] in ("code", "hybrid") and s.get("script"):
            script_path = out / s["script"]
            if write_script_stub(script_path, s["name"]):
                created_stubs.append(s["script"])

    evals_dir = out / "evals"
    evals_dir.mkdir(exist_ok=True)
    evals_path = evals_dir / "trigger.json"
    if not evals_path.exists():
        evals_path.write_text(json.dumps({
            "should_trigger": [],
            "should_not_trigger": [],
        }, indent=2) + "\n")

    type_breakdown = {"code": 0, "inference": 0, "hybrid": 0}
    for s in spec.get("steps", []):
        t = s.get("type")
        if t in type_breakdown:
            type_breakdown[t] += 1

    return {
        "skill_dir": str(out),
        "skill_md_written": True,
        "script_stubs_created": created_stubs,
        "evals_placeholder": str(evals_path) if evals_path.exists() else None,
        "step_count": len(spec.get("steps", [])),
        "type_breakdown": type_breakdown,
    }


def main():
    p = argparse.ArgumentParser(description="Scaffold a new Claude skill from a JSON spec.")
    p.add_argument("--spec", required=True, help="Path to JSON spec file")
    p.add_argument("--out", required=True, help="Output directory for the new skill")
    args = p.parse_args()

    try:
        spec = json.loads(Path(args.spec).read_text())
    except FileNotFoundError:
        print(json.dumps({"error": f"Spec file not found: {args.spec}"}), file=sys.stderr)
        sys.exit(2)
    except json.JSONDecodeError as e:
        print(json.dumps({"error": f"Invalid JSON in spec: {e}"}), file=sys.stderr)
        sys.exit(2)

    for field in ("name", "description"):
        if field not in spec:
            print(json.dumps({"error": f"Spec missing required field: {field}"}), file=sys.stderr)
            sys.exit(2)

    result = scaffold(spec, args.out)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
