export const EVENT_TYPES = Object.freeze({
  PIPELINE_INITIALIZED: 'PipelineInitialized',
  PIPELINE_PAUSED: 'PipelinePaused',
  PIPELINE_RESUMED: 'PipelineResumed',
  PACK_APPLIED: 'PackApplied',
  STAGE_STARTED: 'StageStarted',
  STAGE_COMPLETED: 'StageCompleted',
  STAGE_FAILED: 'StageFailed',
  STAGE_RETRYING: 'StageRetrying',
  STAGE_SKIPPED: 'StageSkipped',
  ARTIFACT_RECORDED: 'ArtifactRecorded',
  GATE_EVALUATED: 'GateEvaluated',
  AGENT_STARTED: 'AgentStarted',
  AGENT_COMPLETED: 'AgentCompleted',
  AGENT_FAILED: 'AgentFailed',
  AGENT_RETRY_SCHEDULED: 'AgentRetryScheduled',
  REVISION_REQUESTED: 'RevisionRequested',
  CONVERSATION_OPENED: 'ConversationOpened',
  CONVERSATION_MESSAGE_APPENDED: 'ConversationMessageAppended',
  CONVERSATION_RESOLVED: 'ConversationResolved',
  TODO_MATERIALIZED: 'TodoMaterialized',
  PLUGIN_DISCOVERED: 'PluginDiscovered',
  PLUGIN_ACTIVATED: 'PluginActivated',
  PLUGIN_HOOK_EXECUTED: 'PluginHookExecuted',
  PLUGIN_HOOK_FAILED: 'PluginHookFailed',
  PLUGINS_REGISTERED: 'PluginsRegistered',
  WAVE_VERIFIED: 'WaveVerified',
  REQUIREMENTS_VERIFIED: 'RequirementsVerified',
  WIP_CHECKPOINT_CREATED: 'WipCheckpointCreated',
  USER_CHOICE_RECORDED: 'UserChoiceRecorded',
} as const);

export type EventType = (typeof EVENT_TYPES)[keyof typeof EVENT_TYPES];

export const EVENT_TYPE_VALUES = Object.freeze(Object.values(EVENT_TYPES) as EventType[]);
