#!/usr/bin/env python3
"""Dynamic call-path census: callables actually entered during one call.

Usage:
    python3 hops_dyn.py <package_dir> --setup "<python statements>" --call "<python expression>" [--own REGEX]

Runs the expression under sys.setprofile and records every Python frame whose
code object lives in a file under <package_dir>. Code objects named
`<lambda>`, `<listcomp>`, `<genexpr>` etc. are counted separately (on Python
>= 3.12 comprehensions are inlined and produce no frame). Class constructors
generated by dataclasses/NamedTuple live in `<string>` and are therefore never
counted -- same as the static tracer.

The number describes ONE execution, not the code: the same entry point can
enter 1 callable on a cache hit and 4 on a miss. Pair it with hops.py, which
enters every reachable arm.

Example:
    python3 hops_dyn.py triple --setup "import layered_routing as L" \\
        --call "L.get_standard({'defaults': {'error': (30, 10)}, 'overrides': {}, 'org_days': None, 'grandfathered': True}, 'error', frozenset({'error'}))"
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import hops  # noqa: E402


def main(argv):
    opts, rest = hops.parse_options(argv[1:])
    if len(rest) < 5 or "--setup" not in rest or "--call" not in rest:
        print(__doc__)
        return 2
    package_dir = os.path.abspath(rest[0])
    setup = rest[rest.index("--setup") + 1]
    call = rest[rest.index("--call") + 1]
    own_rx = re.compile(opts["own"]) if opts["own"] else None
    # A package (has __init__.py) is imported through its parent; putting the
    # package dir itself first would shadow stdlib modules with the same basename
    # (html.py, types.py, parser.py ...). Flat fixture dirs need the dir itself.
    if os.path.exists(os.path.join(package_dir, "__init__.py")):
        sys.path.insert(0, os.path.dirname(package_dir))
    else:
        sys.path.insert(0, package_dir)
    index = hops.build_index(package_dir)
    line_map = {os.path.abspath(m.path): m for m in index.values()}
    ns = {}
    exec(setup, ns)
    entered = []
    counts = {}
    synthetic = {}

    def prof(frame, event, _arg):
        if event != "call":
            return
        code = frame.f_code
        fn = os.path.abspath(code.co_filename)
        if fn not in line_map:
            return
        if code.co_name.startswith("<"):
            k = (line_map[fn].name, code.co_name, code.co_firstlineno)
            synthetic[k] = synthetic.get(k, 0) + 1
            return
        mod = line_map[fn]
        qual = mod.def_lines.get(code.co_firstlineno, code.co_name)
        key = (mod.name, qual)
        counts[key] = counts.get(key, 0) + 1
        if key not in entered:
            entered.append(key)

    sys.setprofile(prof)
    try:
        result = eval(call, ns)
    finally:
        sys.setprofile(None)
    by_module = {}
    for m, _q in entered:
        by_module[m] = by_module.get(m, 0) + 1
    owned = [k for k in entered if own_rx and (own_rx.search(index[k[0]].path) or own_rx.search(k[0]))]
    print(f"call: {call}")
    print(f"result: {result!r}")
    print(f"callables entered: {len(entered)}  (invocations: {sum(counts.values())})")
    if own_rx:
        print(f"branch-owned (module matches {opts['own']!r}): {len(owned)}")
    print("by module: " + ", ".join(f"{m} {n}" for m, n in by_module.items()))
    print("path (first entry order):")
    for i, key in enumerate(entered, 1):
        print(f"  {i:3d} {key[0]}:{key[1]}  x{counts[key]}")
    print(f"comprehension/lambda code objects entered: {sum(synthetic.values())} over {len(synthetic)} sites")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
