#!/usr/bin/env bash
# discover-today.sh — Mine local signals for "what got done" on a given day and
# emit a scannable Markdown digest to stdout. This is the deterministic first
# pass of the dev-diary loop; the model reads the digest, drills into anything
# interesting, then interviews the user before writing the entry.
#
# Usage:
#   discover-today.sh [YYYY-MM-DD]     # default: today, in local time
#
# Sources (each degrades gracefully if absent):
#   1. ~/.claude/history.jsonl        — every typed prompt (epoch-ms timestamp)
#   2. ~/.claude/projects/*/*.jsonl   — session transcripts (ai-title + cwd)
#   3. ~/projects/*                   — git commits authored that day
#
# All time windows are computed in LOCAL time. Transcript records store UTC
# (Z-suffixed) timestamps, so we convert the local window to epoch and compare.

set -euo pipefail

DAY="${1:-$(date +%F)}"
if ! date -d "$DAY" +%F >/dev/null 2>&1; then
  echo "error: '$DAY' is not a valid date (expected YYYY-MM-DD)" >&2
  exit 2
fi
DAY="$(date -d "$DAY" +%F)"
NEXT="$(date -d "$DAY + 1 day" +%F)"

# Local-day boundaries as epoch seconds / milliseconds.
START_S="$(date -d "$DAY 00:00:00" +%s)"
END_S="$(date -d "$NEXT 00:00:00" +%s)"
START_MS=$((START_S * 1000))
END_MS=$((END_S * 1000))

HISTORY="$HOME/.claude/history.jsonl"
PROJECTS_DIR="$HOME/.claude/projects"
CODE_DIR="$HOME/projects"

# fmt_local <epoch-seconds> -> HH:MM
fmt_local() { date -d "@$1" +%H:%M; }

echo "# Discovery digest — $DAY ($(date -d "$DAY" +%A))"
echo
echo "_Local window: $DAY 00:00 → $NEXT 00:00 ($(date +%Z)). Generated by discover-today.sh._"
echo

# ---------------------------------------------------------------------------
# 1. Prompts typed that day (the richest, most compact "what was asked" source)
# ---------------------------------------------------------------------------
echo "## Prompts typed ($DAY)"
echo
if [[ -f "$HISTORY" ]]; then
  count="$(jq -rc --argjson lo "$START_MS" --argjson hi "$END_MS" \
    'select((.timestamp // 0) >= $lo and (.timestamp // 0) < $hi)
     | [ (.timestamp/1000 | floor | strftime("%H:%M")),
         (.project // "?" | sub("^.*/";"")),
         (.display // "" | gsub("\n";" ") | .[0:140]) ]
     | @tsv' "$HISTORY" 2>/dev/null | wc -l)"
  if [[ "$count" -gt 0 ]]; then
    # strftime on the epoch above renders in UTC; re-render the time locally.
    jq -rc --argjson lo "$START_MS" --argjson hi "$END_MS" \
      'select((.timestamp // 0) >= $lo and (.timestamp // 0) < $hi)
       | [ (.timestamp/1000 | floor | tostring),
           (.project // "?" | sub("^.*/";"")),
           (.display // "" | gsub("\n";" ") | .[0:140]) ]
       | @tsv' "$HISTORY" 2>/dev/null \
    | while IFS=$'\t' read -r epoch proj text; do
        printf -- "- %s  \`%s\`  %s\n" "$(fmt_local "$epoch")" "$proj" "$text"
      done
    echo
    echo "_($count prompts)_"
  else
    echo "_No prompts recorded for this day._"
  fi
else
  echo "_history.jsonl not found._"
fi
echo

# ---------------------------------------------------------------------------
# 2. Sessions active that day (ai-title gives a one-line human summary each)
# ---------------------------------------------------------------------------
echo "## Sessions active ($DAY)"
echo
if [[ -d "$PROJECTS_DIR" ]]; then
  found=0
  # Only inspect files whose mtime lands on the target day — cheap pre-filter.
  while IFS= read -r -d '' f; do
    mt="$(date -d "@$(stat -c %Y "$f")" +%F)"
    [[ "$mt" == "$DAY" ]] || continue
    # First human-set title and the working directory for the session.
    # Capture the full jq output and take the first line in the shell — piping
    # jq into `head -1` would SIGPIPE jq and, under `set -o pipefail`, abort the
    # whole script (exit 141).
    title="$(jq -rc 'select(.type=="ai-title") | .aiTitle' "$f" 2>/dev/null || true)"
    title="${title%%$'\n'*}"
    cwd="$(jq -rc 'select(.cwd) | .cwd' "$f" 2>/dev/null || true)"
    cwd="${cwd%%$'\n'*}"
    # Count human turns that fall inside the local window.
    turns="$(jq -rc --arg lo "$START_S" --arg hi "$END_S" \
      'select(.type=="user" and (.timestamp // empty))
       | (.timestamp | sub("\\.[0-9]+Z$";"Z") | fromdateiso8601)
       | select(. >= ($lo|tonumber) and . < ($hi|tonumber))' \
      "$f" 2>/dev/null | wc -l)"
    [[ -z "$title" ]] && title="(untitled session)"
    printf -- "- **%s**  \`%s\`  — %s human turns  _[%s]_\n" \
      "$title" "${cwd:-?}" "$turns" "$(basename "$f" .jsonl | cut -c1-8)"
    found=$((found+1))
  done < <(find "$PROJECTS_DIR" -maxdepth 2 -name '*.jsonl' -print0 2>/dev/null)
  [[ "$found" -eq 0 ]] && echo "_No sessions touched on this day._"
else
  echo "_No ~/.claude/projects directory._"
fi
echo

# ---------------------------------------------------------------------------
# 3. Git commits authored that day across ~/projects
# ---------------------------------------------------------------------------
echo "## Commits authored ($DAY)"
echo
if [[ -d "$CODE_DIR" ]]; then
  any=0
  for repo in "$CODE_DIR"/*/; do
    [[ -d "$repo/.git" ]] || continue
    name="$(basename "$repo")"
    log="$(git -C "$repo" log --all --no-merges \
            --since="$DAY 00:00:00" --until="$NEXT 00:00:00" \
            --date=format-local:%H:%M \
            --pretty='  - %ad `%h` %s' 2>/dev/null || true)"
    if [[ -n "$log" ]]; then
      branch="$(git -C "$repo" rev-parse --abbrev-ref HEAD 2>/dev/null || echo '?')"
      echo "- **$name** _(on \`$branch\`)_"
      echo "$log"
      any=1
    fi
  done
  [[ "$any" -eq 0 ]] && echo "_No commits authored on this day under ~/projects._"
else
  echo "_No ~/projects directory._"
fi
echo

echo "---"
echo "_Next: read anything above that looks significant (drill into a transcript or \`git show\`),"
echo "then interview the user before writing \`entries/$(date -d "$DAY" +%Y)/$DAY.md\`._"
