#!/usr/bin/env python3
"""
gen_existence.py — the existence-script primitive for test-suite-generator (4-A).

The skill's 4-A narrates, in prose, the one correct fail-fast bash idiom plus a
list of "forbidden patterns" that defeat `set -e`. skillwise THEORY.md §3 says a
mechanical artifact described in prose is re-improvised every run, and the
improvised layer is where silent bugs live (an `if`-wrapped check silently
swallowing a failure is precisely that). This script emits the existence script
so the agent never hand-writes the bash: `set -euo pipefail` is always on line 1,
checks always run through a no-`if` helper, and the function check always uses the
broad export-matching regex (direct / default / barrel re-export) the skill
documents — a too-narrow regex can no longer slip in.

It implements `references/sub-modules/existence-extractor.md`. Output is a single
fail-fast shell script. The implementer has not written the code yet, so it is
EXPECTED to fail on first run — that is the contract, not a current-pass demand.

Usage:
    python gen_existence.py <done_when.yaml> [--src src] [--version X.Y.Z] > tests/<feature>/existence.sh
"""

import sys
import argparse

try:
    import yaml
except ImportError:
    sys.stderr.write("gen_existence.py needs PyYAML: pip install pyyaml\n")
    sys.exit(2)

HEADER = """\
#!/usr/bin/env bash
# Generated by test-suite-generator/{version}
# Existence checks for feature: {feature}
# FAIL-FAST: exits on the FIRST missing symbol (set -euo pipefail). Do not convert
# to a count-all-then-exit tally — that defeats errexit (see SKILL 4-A forbidden
# patterns). Expected to FAIL before the implementer writes the code; that is the
# contract, not a current-pass requirement.
set -euo pipefail

SRC="${{1:-{src}}}"

check() {{
  # No `if` and no `||`-with-assignment: those disable errexit and swallow failures.
  local label="$1"; shift
  "$@" >/dev/null 2>&1 || {{ echo "✗ FAIL: $label" >&2; exit 1; }}
  echo "✓ $label"
}}
"""


def esc(s):
    return str(s).replace('"', '\\"')


def emit_check(kind, value, src):
    """Return (label, bash-command-words) for one existence entry."""
    v = esc(value)
    if kind == "file":
        return (f"file {v}", f'test -f "{v}"')
    if kind == "function":
        # Broad export match: direct export, export default, and barrel re-export.
        # (per existence-extractor.md — a narrow regex false-negatives on the latter two)
        name = value
        ts = (rf'export\s+(default\s+)?(class|function|const|let|var)\s+{name}\b'
              rf'|export\s*\{{[^}}]*\b{name}\b')
        return (f"function {name} exported",
                f'rg -qU "{ts}" "$SRC"')
    if kind == "route":
        # value like "POST /api/subscription/cancel"
        parts = str(value).split(None, 1)
        path = parts[1] if len(parts) == 2 else parts[0]
        return (f"route {v}", f'rg -q "{esc(path)}" "$SRC"')
    if kind == "db_field":
        # value like "subscription.status"
        tbl, _, col = str(value).partition(".")
        return (f"db_field {v}", f'rg -q "{esc(col)}" "$SRC"')
    if kind == "frontend_component":
        return (f"frontend_component {v}", f'rg -q "{v}" "$SRC"')
    return (f"{kind} {v}", f'rg -q "{v}" "$SRC"')


def main():
    ap = argparse.ArgumentParser(description="Emit a fail-fast existence.sh from done_when.yaml.")
    ap.add_argument("path")
    ap.add_argument("--src", default="src", help="default source dir (overridable as $1 in the script)")
    ap.add_argument("--version", default="<skill-version>",
                    help="value of SKILL.md frontmatter version: (do NOT hardcode a literal)")
    args = ap.parse_args()

    with open(args.path, encoding="utf-8") as fh:
        doc = yaml.safe_load(fh)
    feature = doc.get("feature", "<feature>")
    existence = doc.get("existence") or []

    out = [HEADER.format(version=args.version, feature=feature, src=args.src)]
    n = 0
    for entry in existence:
        if not isinstance(entry, dict) or len(entry) != 1:
            sys.stderr.write(f"skipping malformed existence entry: {entry!r}\n")
            continue
        kind, value = next(iter(entry.items()))
        label, cmd = emit_check(kind, value, args.src)
        out.append(f'check "{label}" {cmd}')
        n += 1
    out.append(f'echo "✓ All {n} existence checks passed"')
    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
