#!/usr/bin/env node
// Build a plain-markdown catalog of every tech spec under a specs/ tree.
// Portable (no deps), so any agent can read/grep one file to find and
// reference specs, and the plan-review viewer renders it as the landing doc.
//
// Usage: node build-index.js [specs-root]   (default: ./specs)
// Writes <specs-root>/index.md — overwriting any prior catalog.

const fs = require('fs');
const path = require('path');

const root = path.resolve(process.argv[2] || 'specs');
if (!fs.existsSync(root) || !fs.statSync(root).isDirectory()) {
  console.error('spec-browser: no specs directory at ' + root);
  process.exit(1);
}

// A "spec" is any directory under root (excluding root itself) that holds an
// index.md. Walk depth-first, skipping dotdirs.
function findSpecs(dir, rel) {
  const specs = [];
  let entries;
  try { entries = fs.readdirSync(dir, { withFileTypes: true }); }
  catch (e) { return specs; }
  if (rel && entries.some(function (e) { return e.isFile() && e.name === 'index.md'; })) {
    specs.push(rel);
  }
  entries
    .filter(function (e) { return e.isDirectory() && e.name[0] !== '.'; })
    .sort(function (a, b) { return a.name.localeCompare(b.name); })
    .forEach(function (e) {
      specs.push.apply(specs, findSpecs(path.join(dir, e.name), rel ? rel + '/' + e.name : e.name));
    });
  return specs;
}

// A spec's purpose is a "> note" or an opening prose line — never the
// bookkeeping that surrounds it. technical-spec's scaffold opens every
// index.md with a metadata block (**Last updated:**, **Commit:**,
// **Status:**) and follows it with a "## Contents" list, so a naive
// first-non-heading-line rule reports "**Last updated:** 2026-08-13" as the
// purpose of every scaffold-written spec, and skipping only the metadata just
// promotes the first Contents bullet instead. Scanning stops at the first
// "##" section: anything past it is structure, not a description. No purpose
// is an honest "—", which is a prompt to write one.
const META = /^\*{1,2}[^*]+:\*{1,2}/;
const BULLET = /^([-*+]|\d+[.)])\s/;
const COMMENT = /<!--[\s\S]*?-->/g;

function metaOf(rel) {
  let title = rel, purpose = '';
  try {
    const lines = fs.readFileSync(path.join(root, rel, 'index.md'), 'utf8').split('\n');
    for (let i = 0; i < lines.length; i++) {
      const l = lines[i].trim();
      if (!l) continue;
      // An HTML comment is never a purpose — it is invisible in every rendered
      // view of the file, so promoting it into the catalog puts text on the
      // page that the spec itself does not show. This is what lets the
      // scaffold leave a "write your purpose here" prompt in the file without
      // that prompt becoming the description of every new spec.
      if (l.startsWith('<!--')) {
        while (i < lines.length && !lines[i].includes('-->')) i++;
        continue;
      }
      const h = l.match(/^#\s+(.*)/);
      if (h && title === rel) { title = h[1].trim(); continue; }
      const q = l.match(/^>\s*(.*)/);
      if (q) { purpose = block(lines, i, /^>\s?/); break; }
      if (/^#{2,}\s/.test(l)) break;
      if (/^#/.test(l) || META.test(l) || BULLET.test(l)) continue;
      purpose = block(lines, i, null);
      break;
    }
  } catch (e) { /* keep defaults */ }
  // Skipping comment *lines* above stops one swallowing the real purpose
  // below it; stripping inline ones here catches the rest — a trailing
  // "> Purpose. <!-- note -->" or a comment inside the quoted block.
  purpose = purpose.replace(COMMENT, ' ').replace(/\s+/g, ' ').trim();
  return { title: title, purpose: clamp(purpose).replace(/\|/g, '\\|') };
}

// A purpose is a paragraph, not a line. Markdown hard-wraps prose, so taking
// one line cuts the sentence wherever the author's editor happened to wrap —
// "…is the single source". Join the contiguous block instead, stopping at the
// blank line or structural marker that ends it.
function block(lines, start, strip) {
  const out = [];
  for (let i = start; i < lines.length; i++) {
    const l = lines[i].trim();
    if (!l) break;
    if (strip) { if (!strip.test(l)) break; out.push(l.replace(strip, '').trim()); continue; }
    if (/^[#>]/.test(l) || META.test(l) || BULLET.test(l)) break;
    out.push(l);
  }
  return out.join(' ').replace(/\s+/g, ' ').trim();
}

// Keep the table scannable: one sentence, or a word-boundary cut.
function clamp(s) {
  if (s.length <= 200) return s;
  const dot = s.slice(0, 200).lastIndexOf('. ');
  if (dot > 80) return s.slice(0, dot + 1);
  return s.slice(0, s.slice(0, 199).lastIndexOf(' ')) + '…';
}

const specs = findSpecs(root, '');
const date = new Date().toISOString().slice(0, 10);

let md = '# Spec Index\n\n';
md += '> Generated by spec-browser on ' + date + ' — do not edit by hand.\n';
md += '> Regenerate: `node <spec-browser>/references/build-index.js ' + (process.argv[2] || 'specs') + '`\n\n';
md += specs.length + ' spec' + (specs.length === 1 ? '' : 's') + '.\n\n';
md += '| Spec | Purpose | Path |\n|---|---|---|\n';
specs.forEach(function (rel) {
  const m = metaOf(rel);
  md += '| [' + m.title + '](' + rel + '/index.md) | ' + (m.purpose || '—') + ' | `' + rel + '` |\n';
});

fs.writeFileSync(path.join(root, 'index.md'), md);
console.log('wrote ' + path.join(root, 'index.md') + ' (' + specs.length + ' specs)');
